### ISSUE TITLE
MapTR result

### ISSUE THREAD

**Issue by jike5** [jiahaoLjh/MapVectorizationEvalToolkit#1]
Hello, thank you for your excellent work. We tried evaluating the results using this code with MapTR and found that it doesn't match the mAP (raster) from the MapVR paper (mAP_Chamfer matches). We checked the parameter settings, and they are the same as in MapVR's lane_evaluator.py at https://github.com/ZhangGongjie/MapVR/blob/main/tools/lane_evaluator.py

<img width="659" alt="image" src="https://github.com/jiahaoLjh/MapVectorizationEvalToolkit/assets/58059573/2ed64da3-78aa-4847-b63d-b604e50deff5">

Is there any modification that I missed? Thx!

**Comment by ZhangGongjie** [comment]
May I know which MapTR version are you referring to?  Is it MapTR-Res50-CameraOnlyModality-24epoch?

**Comment by ZhangGongjie** [comment]
Please note that I have left BlackSesameTech and thus I can no longer access my experimental log. I would be happy to try to reproduce the results again on my local setting, and try to find what's wrong.

**Comment by jike5** [comment]
> May I know which MapTR version are you referring to? Is it MapTR-Res50-CameraOnlyModality-24epoch?

Yes, this is the checkpoint I used: [link](https://drive.google.com/file/d/1n1FUFnRqdskvmpLdnsuX_VK6pET19h95/view?usp=share_link). I solved the problem by using the evaluation code in the MapVR repository. However, I noticed that the configuration parameters in the MapVR repository and this repository appear to be the same. 😂

**Comment by jike5** [comment]
> Please note that I have left BlackSesameTech and thus I can no longer access my experimental log. I would be happy to try to reproduce the results again on my local setting, and try to find what's wrong.

Thanks a lot! Since I have found a way to solve my problem, I will close the issue. If you have time, you can try using the checkpoint I mentioned above.
